# Quarkus Configuration
quarkus.http.limits.max-body-size=100M
quarkus.resteasy-reactive.multipart.input-part.default-charset=UTF-8

# Timeouts for heavy processing
quarkus.http.read-timeout=300s
quarkus.http.write-timeout=300s
quarkus.http.idle-timeout=300s

# Comic Trip settings
comic-trip.picture.bucket=bkt-prj-s-sandbox-lipser-5013-test1
